apiVersion: skaffold/v4beta6
kind: Config 
build:
  artifacts:
    - image: us.gcr.io/ticketing-dev-399516/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-399516
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
  